### ISSUE TITLE
Banner Update: Fall motif

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/fiesta-covid#19]
Please update the Fiesta Banner in the theme to Fall. 
<img width="1259" alt="Screen Shot 2020-10-08 at 10 10 15" src="https://user-images.githubusercontent.com/46387723/95470170-78940e00-094e-11eb-9852-71a429c8b4c6.png">

**Comment by lionelmann** [comment]
See https://github.com/hypenotic/fiestafarms/commit/565e0054b6baf13c6bd61f681174b329fec71ba2

This issue was in the incorrect repo. See link above. This is done.
